{"resourceType":"ValueSet","id":"2.16.840.1.113762.1.4.1200.152","meta":{"versionId":"11","lastUpdated":"2021-07-21T01:02:04.000-04:00","profile":["http://hl7.org/fhir/StructureDefinition/shareablevalueset","http://hl7.org/fhir/us/cqfmeasures/StructureDefinition/publishable-valueset-cqfm"]},"extension":[{"url":"http://hl7.org/fhir/StructureDefinition/valueset-author","valueString":"Cliniwiz Author"},{"url":"http://hl7.org/fhir/StructureDefinition/resource-lastReviewDate","valueDate":"2022-12-15"},{"url":"http://hl7.org/fhir/StructureDefinition/valueset-effectiveDate","valueDate":"2021-07-21"}],"url":"http://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113762.1.4.1200.152","identifier":[{"system":"urn:ietf:rfc:3986","value":"urn:oid:2.16.840.1.113762.1.4.1200.152"}],"version":"20210721","name":"COVID19Diagnosis","title":"COVID 19 Diagnosis","status":"active","experimental":false,"date":"2021-07-21T01:02:04-04:00","publisher":"Cliniwiz Steward","jurisdiction":[{"coding":[{"system":"urn:iso:std:iso:3166","code":"US"}]}],"purpose":"(Clinical Focus: ),(Data Element Scope: ),(Inclusion Criteria: ),(Exclusion Criteria: )","compose":{"include":[{"system":"http://snomed.info/sct","concept":[{"code":"840539006","display":"Disease caused by Severe acute respiratory syndrome coronavirus 2 (disorder)"}]}]},"expansion":{"identifier":"urn:uuid:3093687c-97bf-476e-9e1a-44fb0de440f1","timestamp":"2023-12-10T23:15:01-05:00","total":1,"contains":[{"system":"http://snomed.info/sct","version":"http://snomed.info/sct/731000124108/version/20230901","code":"840539006","display":"Disease caused by severe acute respiratory syndrome coronavirus 2 (disorder)"}]}}