{"resourceType":"ValueSet","id":"2.16.840.1.113883.3.3616.200.110.102.6274","meta":{"versionId":"9","lastUpdated":"2020-11-03T01:00:34.000-05:00"},"url":"http://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113883.3.3616.200.110.102.6274","version":"20201103","name":"COVID19 SNOMED Value Set for COVID19 Suspected Infection","status":"active","date":"2020-11-03T01:00:35-05:00","publisher":"Clinical Architecture","compose":{"include":[{"system":"http://snomed.info/sct","version":"http://snomed.info/sct/731000124108/version/20220301","concept":[{"code":"840544004","display":"Suspected disease caused by Severe acute respiratory coronavirus 2 (situation)"}]}]},"expansion":{"identifier":"urn:uuid:92432511-3abc-44d3-b79c-2ee0f16e2ed8","timestamp":"2022-06-10T06:29:49-04:00","total":1,"offset":0,"parameter":[{"name":"count","valueInteger":1000},{"name":"offset","valueInteger":0}],"contains":[{"system":"http://snomed.info/sct","version":"http://snomed.info/sct/731000124108/version/20220301","code":"840544004","display":"Suspected disease caused by Severe acute respiratory coronavirus 2 (situation)"}]}}